# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  host: localhost
  secret_key_base: 57f2d9efad50d9a79dd661e899f8f556b1fee1df18c5abbdd871cfb6b6d36715ea1b25d18db8b6703d62c15c311f232e20202d231ccdebc3d3e7c54f4ca13b73
  slack_webhook_url: https://hooks.slack.com/services/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

test:
  host: localhost
  secret_key_base: 819f8dcb9197007d490399b78aa07f349d1f9fd8967f80c344580c74d62326adf7ed889f66927ca74085d8e70f141734dd8c869c4866809e4771ac5126c3e770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  host: wamui-dev.herokuapp.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
